---
name: Build - Windows

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: '-j 2'

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        buildtype: [windows-release]
        include:
          - os: windows-2022
            triplet: x64-windows
            packages: >
              sccache

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: CCache
        uses: hendrikmuhs/ccache-action@main
        with:
          max-size: "1G"
          variant: "sccache"
          key: ccache-${{ matrix.os }}-${{ matrix.buildtype }}
          restore-keys: |
            ccache-${{ matrix.os }}

      - name: Restore artifacts and install vcpkg
        uses: lukka/run-vcpkg@main
        with:
          vcpkgGitCommitId: f14984af3738e69f197bf0e647a8dca12de92996

      - name: Get latest CMake
        uses: lukka/get-cmake@main

      - name: Run CMake
        uses: lukka/run-cmake@main
        with:
          configurePreset: ${{ matrix.buildtype }}
          buildPreset: ${{ matrix.buildtype }}

      - name: Create and Upload Artifact (exe)
        uses: actions/upload-artifact@main
        with:
          name: rme-${{ matrix.buildtype }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/rme.exe

      - name: Create and Upload Artifact (dlls)
        uses: actions/upload-artifact@main
        with:
          name: otclient-${{ matrix.buildtype }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/*.dll

